/*
 * Copyright (C) 2018-2025 Toshiaki Maki <makingx@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package am.ik.yavi.arguments;

import java.util.Locale;
import java.util.Objects;
import java.util.function.Function;
import java.util.function.Supplier;

import am.ik.yavi.core.ConstraintContext;
import am.ik.yavi.core.ConstraintGroup;
import am.ik.yavi.core.ConstraintViolationsException;
import am.ik.yavi.core.Validated;
import am.ik.yavi.core.ValueValidator;
import am.ik.yavi.jsr305.Nullable;

/**
 * Generated by https://github.com/making/yavi/blob/develop/scripts/generate-args.sh
 *
 * @since 0.3.0
 */
@FunctionalInterface
public interface Arguments2Validator<A1, A2, X> {

	/**
	 * Convert an Arguments1Validator that validates Arguments2 to an Arguments2Validator
	 * @param validator validator for Arguments2
	 * @param <A1> type of first argument
	 * @param <A2> type of argument at position 2
	 * @param <X> target result type
	 * @return arguments2 validator that takes arguments directly
	 * @since 0.16.0
	 */
	static <A1, A2, X> Arguments2Validator<A1, A2, X> unwrap(Arguments1Validator<Arguments2<A1, A2>, X> validator) {
		return new Arguments2Validator<A1, A2, X>() {
			@Override
			public Validated<X> validate(@Nullable A1 a1, @Nullable A2 a2, Locale locale,
					ConstraintContext constraintContext) {
				return validator.validate(Arguments.of(a1, a2), locale, constraintContext);
			}

			@Override
			public Arguments2Validator<A1, A2, Supplier<X>> lazy() {
				return Arguments2Validator.unwrap(validator.lazy());
			}
		};
	}

	Validated<X> validate(@Nullable A1 a1, @Nullable A2 a2, Locale locale, ConstraintContext constraintContext);

	/**
	 * Convert this validator to one that validates Arguments2 as a single object.
	 * @return a validator that takes an Arguments2
	 * @since 0.16.0
	 */
	default Arguments1Validator<Arguments2<A1, A2>, X> wrap() {
		final Arguments2Validator<A1, A2, Supplier<X>> lazy = this.lazy();
		return new Arguments1Validator<Arguments2<A1, A2>, X>() {
			@Override
			public Validated<X> validate(Arguments2<A1, A2> args, Locale locale, ConstraintContext constraintContext) {
				final Arguments2<? extends A1, ? extends A2> nonNullArgs = Objects.requireNonNull(args);
				return Arguments2Validator.this.validate(nonNullArgs.arg1(), nonNullArgs.arg2(), locale,
						constraintContext);
			}

			@Override
			public Arguments1Validator<Arguments2<A1, A2>, Supplier<X>> lazy() {
				return lazy.wrap();
			}
		};
	}

	/**
	 * @since 0.7.0
	 */
	default <X2> Arguments2Validator<A1, A2, X2> andThen(Function<? super X, ? extends X2> mapper) {
		final Arguments2Validator<A1, A2, Supplier<X>> lazy = this.lazy();
		return new Arguments2Validator<A1, A2, X2>() {
			@Override
			public Validated<X2> validate(A1 a1, A2 a2, Locale locale, ConstraintContext constraintContext) {
				return Arguments2Validator.this.validate(a1, a2, locale, constraintContext).map(mapper);
			}

			@Override
			public Arguments2Validator<A1, A2, Supplier<X2>> lazy() {
				return lazy
					.andThen((Function<Supplier<X>, Supplier<X2>>) xSupplier -> () -> mapper.apply(xSupplier.get()));
			}
		};
	}

	/**
	 * @since 0.11.0
	 */
	default <X2> Arguments2Validator<A1, A2, X2> andThen(ValueValidator<? super X, X2> validator) {
		final Arguments2Validator<A1, A2, Supplier<X>> lazy = this.lazy();
		return new Arguments2Validator<A1, A2, X2>() {
			@Override
			public Validated<X2> validate(A1 a1, A2 a2, Locale locale, ConstraintContext constraintContext) {
				return Arguments2Validator.this.validate(a1, a2, locale, constraintContext)
					.flatMap(v -> validator.validate(v, locale, constraintContext));
			}

			@Override
			public Arguments2Validator<A1, A2, Supplier<X2>> lazy() {
				return lazy.andThen((xSupplier, locale, constraintContext) -> validator
					.validate(Objects.requireNonNull(xSupplier).get(), locale, constraintContext)
					.map(x2 -> () -> x2));
			}
		};
	}

	/**
	 * @since 0.7.0
	 */
	default <A> Arguments1Validator<A, X> compose(
			Function<? super A, ? extends Arguments2<? extends A1, ? extends A2>> mapper) {
		final Arguments2Validator<A1, A2, Supplier<X>> lazy = this.lazy();
		return new Arguments1Validator<A, X>() {
			@Override
			public Validated<X> validate(A a, Locale locale, ConstraintContext constraintContext) {
				final Arguments2<? extends A1, ? extends A2> args = mapper.apply(a);
				return Arguments2Validator.this.validate(args.arg1(), args.arg2(), locale, constraintContext);
			}

			@Override
			public Arguments1Validator<A, Supplier<X>> lazy() {
				return lazy.compose(mapper);
			}
		};
	}

	/**
	 * @since 0.10.0
	 */
	default Arguments2Validator<A1, A2, Supplier<X>> lazy() {
		throw new UnsupportedOperationException("lazy is not implemented!");
	}

	default Validated<X> validate(@Nullable A1 a1, @Nullable A2 a2) {
		return this.validate(a1, a2, Locale.getDefault(), ConstraintGroup.DEFAULT);
	}

	default Validated<X> validate(@Nullable A1 a1, @Nullable A2 a2, ConstraintContext constraintContext) {
		return this.validate(a1, a2, Locale.getDefault(), constraintContext);
	}

	default Validated<X> validate(@Nullable A1 a1, @Nullable A2 a2, Locale locale) {
		return this.validate(a1, a2, locale, ConstraintGroup.DEFAULT);
	}

	default X validated(@Nullable A1 a1, @Nullable A2 a2) throws ConstraintViolationsException {
		return this.validate(a1, a2).orElseThrow(ConstraintViolationsException::new);
	}

	default X validated(@Nullable A1 a1, @Nullable A2 a2, ConstraintContext constraintContext)
			throws ConstraintViolationsException {
		return this.validate(a1, a2, constraintContext).orElseThrow(ConstraintViolationsException::new);
	}

	default X validated(@Nullable A1 a1, @Nullable A2 a2, Locale locale) throws ConstraintViolationsException {
		return this.validate(a1, a2, locale).orElseThrow(ConstraintViolationsException::new);
	}

	default X validated(@Nullable A1 a1, @Nullable A2 a2, Locale locale, ConstraintContext constraintContext)
			throws ConstraintViolationsException {
		return this.validate(a1, a2, locale, constraintContext).orElseThrow(ConstraintViolationsException::new);
	}

}
