/*
 * Copyright (C) 2018-2021 Toshiaki Maki <makingx@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package am.ik.yavi.arguments;

import am.ik.yavi.fn.Function8;
import am.ik.yavi.fn.Validations;

/**
 * Generated by https://github.com/making/yavi/blob/develop/scripts/generate-args.sh
 *
 * @since 0.7.0
 */
public class Arguments8Mapping<A, R1, R2, R3, R4, R5, R6, R7, R8> {
	protected final Arguments1Validator<A, R1> v1;

	protected final Arguments1Validator<A, R2> v2;

	protected final Arguments1Validator<A, R3> v3;

	protected final Arguments1Validator<A, R4> v4;

	protected final Arguments1Validator<A, R5> v5;

	protected final Arguments1Validator<A, R6> v6;

	protected final Arguments1Validator<A, R7> v7;

	protected final Arguments1Validator<A, R8> v8;

	public Arguments8Mapping(Arguments1Validator<A, R1> v1, Arguments1Validator<A, R2> v2,
			Arguments1Validator<A, R3> v3, Arguments1Validator<A, R4> v4,
			Arguments1Validator<A, R5> v5, Arguments1Validator<A, R6> v6,
			Arguments1Validator<A, R7> v7, Arguments1Validator<A, R8> v8) {
		this.v1 = v1;
		this.v2 = v2;
		this.v3 = v3;
		this.v4 = v4;
		this.v5 = v5;
		this.v6 = v6;
		this.v7 = v7;
		this.v8 = v8;
	}

	public <X> Arguments1Validator<A, X> apply(
			Function8<R1, R2, R3, R4, R5, R6, R7, R8, X> f) {
		return (a, locale, constraintGroup) -> Validations.apply(f,
				this.v1.validate(a, locale, constraintGroup),
				this.v2.validate(a, locale, constraintGroup),
				this.v3.validate(a, locale, constraintGroup),
				this.v4.validate(a, locale, constraintGroup),
				this.v5.validate(a, locale, constraintGroup),
				this.v6.validate(a, locale, constraintGroup),
				this.v7.validate(a, locale, constraintGroup),
				this.v8.validate(a, locale, constraintGroup));
	}

	public <R9> Arguments9Mapping<A, R1, R2, R3, R4, R5, R6, R7, R8, R9> map9(
			Arguments1Validator<A, R9> v9) {
		return new Arguments9Mapping<>(v1, v2, v3, v4, v5, v6, v7, v8, v9);
	}
}
