/*
 * Copyright (C) 2018-2024 Toshiaki Maki <makingx@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package am.ik.yavi.builder;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.Year;
import java.time.YearMonth;
import java.time.ZonedDateTime;
import java.util.function.Function;

import am.ik.yavi.arguments.Arguments1;
import am.ik.yavi.arguments.ArgumentsValidators;
import am.ik.yavi.arguments.Arguments10Validator;
import am.ik.yavi.constraint.BigDecimalConstraint;
import am.ik.yavi.constraint.BigIntegerConstraint;
import am.ik.yavi.constraint.BooleanConstraint;
import am.ik.yavi.constraint.CharSequenceConstraint;
import am.ik.yavi.constraint.DoubleConstraint;
import am.ik.yavi.constraint.EnumConstraint;
import am.ik.yavi.constraint.FloatConstraint;
import am.ik.yavi.constraint.InstantConstraint;
import am.ik.yavi.constraint.IntegerConstraint;
import am.ik.yavi.constraint.LocalDateTimeConstraint;
import am.ik.yavi.constraint.LocalTimeConstraint;
import am.ik.yavi.constraint.LongConstraint;
import am.ik.yavi.constraint.ObjectConstraint;
import am.ik.yavi.constraint.OffsetDateTimeConstraint;
import am.ik.yavi.constraint.ShortConstraint;
import am.ik.yavi.constraint.YearConstraint;
import am.ik.yavi.constraint.YearMonthConstraint;
import am.ik.yavi.constraint.ZonedDateTimeConstraint;
import am.ik.yavi.core.ValueValidator;
import am.ik.yavi.fn.Function10;

/**
 * Generated by https://github.com/making/yavi/blob/develop/scripts/generate-args.sh
 *
 * @since 0.14.0
 */
public final class Arguments10ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10> {

	final ValueValidator<A1, A1> v1;

	final ValueValidator<A2, A2> v2;

	final ValueValidator<A3, A3> v3;

	final ValueValidator<A4, A4> v4;

	final ValueValidator<A5, A5> v5;

	final ValueValidator<A6, A6> v6;

	final ValueValidator<A7, A7> v7;

	final ValueValidator<A8, A8> v8;

	final ValueValidator<A9, A9> v9;

	final ValueValidator<A10, A10> v10;

	public Arguments10ValidatorBuilder(ValueValidator<A1, A1> v1,
			ValueValidator<A2, A2> v2, ValueValidator<A3, A3> v3,
			ValueValidator<A4, A4> v4, ValueValidator<A5, A5> v5,
			ValueValidator<A6, A6> v6, ValueValidator<A7, A7> v7,
			ValueValidator<A8, A8> v8, ValueValidator<A9, A9> v9,
			ValueValidator<A10, A10> v10) {
		this.v1 = v1;
		this.v2 = v2;
		this.v3 = v3;
		this.v4 = v4;
		this.v5 = v5;
		this.v6 = v6;
		this.v7 = v7;
		this.v8 = v8;
		this.v9 = v9;
		this.v10 = v10;
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, BigDecimal> _bigDecimal(
			String name,
			Function<BigDecimalConstraint<Arguments1<BigDecimal>>, BigDecimalConstraint<Arguments1<BigDecimal>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				BigDecimalValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, BigDecimal> _bigDecimal(
			String name) {
		return this._bigDecimal(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, BigInteger> _bigInteger(
			String name,
			Function<BigIntegerConstraint<Arguments1<BigInteger>>, BigIntegerConstraint<Arguments1<BigInteger>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				BigIntegerValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, BigInteger> _bigInteger(
			String name) {
		return this._bigInteger(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Boolean> _boolean(
			String name,
			Function<BooleanConstraint<Arguments1<Boolean>>, BooleanConstraint<Arguments1<Boolean>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				BooleanValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Boolean> _boolean(
			String name) {
		return this._boolean(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Double> _double(
			String name,
			Function<DoubleConstraint<Arguments1<Double>>, DoubleConstraint<Arguments1<Double>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				DoubleValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Double> _double(
			String name) {
		return this._double(name, Function.identity());
	}

	public <E extends Enum<E>> Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, E> _enum(
			String name,
			Function<EnumConstraint<Arguments1<E>, E>, EnumConstraint<Arguments1<E>, E>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				EnumValidatorBuilder.of(name, constraints).build());
	}

	public <E extends Enum<E>> Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, E> _enum(
			String name) {
		return this._enum(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Float> _float(
			String name,
			Function<FloatConstraint<Arguments1<Float>>, FloatConstraint<Arguments1<Float>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				FloatValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Float> _float(
			String name) {
		return this._float(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Instant> _instant(
			String name,
			Function<InstantConstraint<Arguments1<Instant>>, InstantConstraint<Arguments1<Instant>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				InstantValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Instant> _instant(
			String name) {
		return this._instant(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Integer> _integer(
			String name,
			Function<IntegerConstraint<Arguments1<Integer>>, IntegerConstraint<Arguments1<Integer>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				IntegerValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Integer> _integer(
			String name) {
		return this._integer(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, LocalDateTime> _localDateTime(
			String name,
			Function<LocalDateTimeConstraint<Arguments1<LocalDateTime>>, LocalDateTimeConstraint<Arguments1<LocalDateTime>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				LocalDateTimeValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, LocalDateTime> _localDateTime(
			String name) {
		return this._localDateTime(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, LocalTime> _localTime(
			String name,
			Function<LocalTimeConstraint<Arguments1<LocalTime>>, LocalTimeConstraint<Arguments1<LocalTime>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				LocalTimeValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, LocalTime> _localTime(
			String name) {
		return this._localTime(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Long> _long(
			String name,
			Function<LongConstraint<Arguments1<Long>>, LongConstraint<Arguments1<Long>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				LongValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Long> _long(
			String name) {
		return this._long(name, Function.identity());
	}

	public <T> Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, T> _object(
			String name,
			Function<ObjectConstraint<Arguments1<T>, T>, ObjectConstraint<Arguments1<T>, T>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				ObjectValidatorBuilder.of(name, constraints).build());
	}

	public <T> Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, T> _object(
			String name) {
		return this._object(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, OffsetDateTime> _offsetDateTime(
			String name,
			Function<OffsetDateTimeConstraint<Arguments1<OffsetDateTime>>, OffsetDateTimeConstraint<Arguments1<OffsetDateTime>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				OffsetDateTimeValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, OffsetDateTime> _offsetDateTime(
			String name) {
		return this._offsetDateTime(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Short> _short(
			String name,
			Function<ShortConstraint<Arguments1<Short>>, ShortConstraint<Arguments1<Short>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				ShortValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Short> _short(
			String name) {
		return this._short(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, String> _string(
			String name,
			Function<CharSequenceConstraint<Arguments1<String>, String>, CharSequenceConstraint<Arguments1<String>, String>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				StringValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, String> _string(
			String name) {
		return this._string(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, YearMonth> _yearMonth(
			String name,
			Function<YearMonthConstraint<Arguments1<YearMonth>>, YearMonthConstraint<Arguments1<YearMonth>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				YearMonthValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, YearMonth> _yearMonth(
			String name) {
		return this._yearMonth(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Year> _year(
			String name,
			Function<YearConstraint<Arguments1<Year>>, YearConstraint<Arguments1<Year>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				YearValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, Year> _year(
			String name) {
		return this._year(name, Function.identity());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, ZonedDateTime> _zonedDateTime(
			String name,
			Function<ZonedDateTimeConstraint<Arguments1<ZonedDateTime>>, ZonedDateTimeConstraint<Arguments1<ZonedDateTime>>> constraints) {
		return new Arguments11ValidatorBuilder<>(this.v1, this.v2, this.v3, this.v4,
				this.v5, this.v6, this.v7, this.v8, this.v9, this.v10,
				ZonedDateTimeValidatorBuilder.of(name, constraints).build());
	}

	public Arguments11ValidatorBuilder<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, ZonedDateTime> _zonedDateTime(
			String name) {
		return this._zonedDateTime(name, Function.identity());
	}

	public <R> Arguments10Validator<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R> apply(
			Function10<A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, R> f) {
		return ArgumentsValidators.split(this.v1, this.v2, this.v3, this.v4, this.v5,
				this.v6, this.v7, this.v8, this.v9, this.v10).apply(f);
	}

}
