/*
 * Copyright (C) 2018-2021 Toshiaki Maki <makingx@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package am.ik.yavi.fn;

import java.util.List;

/**
 * Generated by
 * https://github.com/making/yavi/blob/develop/scripts/generate-applicative.sh
 *
 * @since 0.6.0
 */
public class Composing1<E, T1> {
	protected final Validation<E, T1> v1;

	public Composing1(Validation<E, T1> v1) {
		this.v1 = v1;
	}

	public <R> Validation<E, R> apply(Function1<T1, R> f) {
		return v1.apply(Validation.success(f.curried()));
	}

	public <T2> Composing2<E, T1, T2> compose(Validation<E, T2> v2) {
		return new Composing2<>(v1, v2);
	}
}
