/*
 * Copyright (C) 2018-2021 Toshiaki Maki <makingx@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package am.ik.yavi.fn;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

/**
 * Generated by
 * https://github.com/making/yavi/blob/develop/scripts/generate-applicative.sh
 *
 * @since 0.6.0
 */
public class Validations {
	public static <E, T1> Composing1<E, T1> compose(Validation<E, T1> v1) {
		return new Composing1<>(v1);
	}

	public static <E, T1, T2> Composing2<E, T1, T2> compose(Validation<E, T1> v1,
			Validation<E, T2> v2) {
		return new Composing2<>(v1, v2);
	}

	public static <E, T1, T2, T3> Composing3<E, T1, T2, T3> compose(Validation<E, T1> v1,
			Validation<E, T2> v2, Validation<E, T3> v3) {
		return new Composing3<>(v1, v2, v3);
	}

	public static <E, T1, T2, T3, T4> Composing4<E, T1, T2, T3, T4> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4) {
		return new Composing4<>(v1, v2, v3, v4);
	}

	public static <E, T1, T2, T3, T4, T5> Composing5<E, T1, T2, T3, T4, T5> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5) {
		return new Composing5<>(v1, v2, v3, v4, v5);
	}

	public static <E, T1, T2, T3, T4, T5, T6> Composing6<E, T1, T2, T3, T4, T5, T6> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6) {
		return new Composing6<>(v1, v2, v3, v4, v5, v6);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7> Composing7<E, T1, T2, T3, T4, T5, T6, T7> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7) {
		return new Composing7<>(v1, v2, v3, v4, v5, v6, v7);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8> Composing8<E, T1, T2, T3, T4, T5, T6, T7, T8> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8) {
		return new Composing8<>(v1, v2, v3, v4, v5, v6, v7, v8);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9> Composing9<E, T1, T2, T3, T4, T5, T6, T7, T8, T9> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9) {
		return new Composing9<>(v1, v2, v3, v4, v5, v6, v7, v8, v9);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Composing10<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10) {
		return new Composing10<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Composing11<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11) {
		return new Composing11<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Composing12<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12) {
		return new Composing12<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Composing13<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13) {
		return new Composing13<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Composing14<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14) {
		return new Composing14<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
				v14);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Composing15<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14, Validation<E, T15> v15) {
		return new Composing15<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
				v14, v15);
	}

	public static <E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Composing16<E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> compose(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14, Validation<E, T15> v15,
			Validation<E, T16> v16) {
		return new Composing16<>(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13,
				v14, v15, v16);
	}

	public static <R, E, T1> Validation<List<E>, R> apply(Validation<E, T1> v1,
			Function1<T1, R> f) {
		return compose(v1).apply(f);
	}

	public static <R, E, T1, T2> Validation<List<E>, R> apply(Validation<E, T1> v1,
			Validation<E, T2> v2, Function2<T1, T2, R> f) {
		return compose(v1, v2).apply(f);
	}

	public static <R, E, T1, T2, T3> Validation<List<E>, R> apply(Validation<E, T1> v1,
			Validation<E, T2> v2, Validation<E, T3> v3, Function3<T1, T2, T3, R> f) {
		return compose(v1, v2, v3).apply(f);
	}

	public static <R, E, T1, T2, T3, T4> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Function4<T1, T2, T3, T4, R> f) {
		return compose(v1, v2, v3, v4).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5,
			Function5<T1, T2, T3, T4, T5, R> f) {
		return compose(v1, v2, v3, v4, v5).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Function6<T1, T2, T3, T4, T5, T6, R> f) {
		return compose(v1, v2, v3, v4, v5, v6).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Function7<T1, T2, T3, T4, T5, T6, T7, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8,
			Function8<T1, T2, T3, T4, T5, T6, T7, T8, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Function9<T1, T2, T3, T4, T5, T6, T7, T8, T9, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10,
			Function10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11,
			Function11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Function12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13,
			Function13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13).apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14,
			Function14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14)
				.apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14, Validation<E, T15> v15,
			Function15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15)
				.apply(f);
	}

	public static <R, E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> Validation<List<E>, R> apply(
			Validation<E, T1> v1, Validation<E, T2> v2, Validation<E, T3> v3,
			Validation<E, T4> v4, Validation<E, T5> v5, Validation<E, T6> v6,
			Validation<E, T7> v7, Validation<E, T8> v8, Validation<E, T9> v9,
			Validation<E, T10> v10, Validation<E, T11> v11, Validation<E, T12> v12,
			Validation<E, T13> v13, Validation<E, T14> v14, Validation<E, T15> v15,
			Validation<E, T16> v16,
			Function16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, R> f) {
		return compose(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15,
				v16).apply(f);
	}

	public static <E, T> Validation<List<E>, List<T>> sequence(
			Iterable<Validation<List<E>, T>> validations) {
		final List<E> errors = new ArrayList<>();
		final List<T> values = new ArrayList<>();
		for (Validation<List<E>, T> validation : validations) {
			if (!validation.isValid()) {
				errors.addAll(validation.error());
			}
			else if (errors.isEmpty()) {
				values.add(validation.value());
			}
		}
		return errors.isEmpty() ? Validation.success(values) : Validation.failure(errors);
	}

	public static <E, T, U> Validation<List<E>, List<U>> traverse(Iterable<T> values,
			Function<T, Validation<List<E>, U>> mapper) {
		return sequence(StreamSupport.stream(values.spliterator(), false).map(mapper)
				.collect(Collectors.toList()));
	}
}
