name: Java CI with Maven

on:
  push:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
    - .springjavaformatconfig
  pull_request:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .springjavaformatconfig
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8.x, 11.x, 17.x, 21.x]
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v6
      with:
        java-version: ${{ matrix.java }}
        distribution: 'liberica'
        cache: maven
    - name: Unit Tests
      if: matrix.java != '8.x'
      run: ./mvnw -V --no-transfer-progress clean test
    - name: Unit Tests with Coverage
      if: matrix.java == '8.x'
      run: ./mvnw -V --no-transfer-progress clean jacoco:prepare-agent test jacoco:report
    - name: Build Javadoc
      if: matrix.java == '8.x'
      run: ./mvnw -V --no-transfer-progress javadoc:jar
  deploy:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v7
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v4.0.0
      with:
        exportToken: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/maven_central username | MAVEN_CENTRAL_USERNAME ;
          kv/data/cicd/maven_central password | MAVEN_CENTRAL_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
    - name: Set up JDK 8
      uses: actions/setup-java@v6
      with:
        java-version: '8'
        distribution: 'liberica'
        cache: maven
        gpg-private-key: ${{ steps.secrets.outputs.GPG_SECRING }}
        gpg-passphrase: ${{ steps.secrets.outputs.GPG_PASSPHRASE }}
    - name: Generates Maven Settings
      uses: s4u/maven-settings-action@v4.0.0
      with:
        servers: |
          [{
              "id": "central",
              "username": "${{ steps.secrets.outputs.MAVEN_CENTRAL_USERNAME }}",
              "password": "${{ steps.secrets.outputs.MAVEN_CENTRAL_PASSWORD }}"
          }]
    - name: Deploy to Maven Central
      run: |
        set -e
        ./mvnw -V \
            javadoc:jar \
            source:jar \
            package \
            org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign \
            deploy \
            --no-transfer-progress \
            -Dgpg.passphrase=${GPG_PASSPHRASE} \
            -DskipTests=true
    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self || true
